### ISSUE TITLE
DocumentFactory is not thread safe when SentenceDetectorMENL is used

### ISSUE THREAD

**Issue by SchmaR** [sebastianarnold/TeXoo#18]
`SentenceDetectorMENL.java` holds a reference to _sentProbs_ on instance level. Its actually an ArrayList which is only used in `sentPosDetect(String s)`. In the first line of this method all values are discarded. Therefore, it looks senseful to me to make _sentProbs_ to a local variable. https://github.com/sebastianarnold/TeXoo/blob/e68d0e1c98abe5cb940a794c9f07e86ed3966a83/texoo-core/src/main/java/de/datexis/preprocess/SentenceDetectorMENL.java#L70-L75

**Comment by sebastianarnold** [comment]
I have fixed this last week in commits 27ad7307a08291a8913b8c16324865cf7db1d6ce and d53110b02284c187b80b3a1ea67ad20127eac0af 
Can you pelase try the development branch or very latest 1.1.2-SNAPSHOT in maven repo? If it works for you, I could release a new stable version soon.

**Comment by sebastianarnold** [comment]
...and 974697763a0e704be9adc621623a8770595c0a6a of course, which addresses exactly your suggestion.
