### ISSUE TITLE
TrainEntityRecognition.java in TeXoo examples has an uncaught IOExecption Error when compiling

### ISSUE THREAD

**Issue by SchmaR** [sebastianarnold/TeXoo#25]
Due to the reference to the snapshot version as reported here https://github.com/sebastianarnold/TeXoo/issues/23 . TrainEntityRecognition.java in TeXoo examples has an up to now uncaught IOExecption Error when compiling which nobody recognized so far. 

btw: Why is our Jenkins build not complaining?

**Comment by sebastianarnold** [comment]
Good point, the examples are not part of TeXoo deployment, so Jenkins is not compiling them...
