### ISSUE TITLE
DocumentFactory.createSentenceFromString() might corrupt offsets

### ISSUE THREAD

**Issue by sebastianarnold** [sebastianarnold/TeXoo#31]
When merging Tokens into a new Sentence, the following method is called:
https://github.com/sebastianarnold/TeXoo/blob/14e6724ea66f4cc6d7fb3ebd1f8204cdc8467928/texoo-core/src/main/java/de/datexis/preprocess/DocumentFactory.java#L312

However, this only works as a "repair" for space-separated tokenized Input. Something like this is probably already called when the Tokens are instantiated and does not need to be called again.

Instead, we need to join the Tokens with respect to their natural offsets.

TODO: Fix the case for non-tokenized input
TODO: Unit Test the case for both tokenized and non-tokenized input

**Comment by SchmaR** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix DocumentFactory.createSentenceFromString() might corrupt offsets in TeXoo](https://trello.com/c/RODGCmBu/342-fix-documentfactorycreatesentencefromstring-might-corrupt-offsets-in-texoo)
