### ISSUE TITLE
Document.clearAnnotations() throws NullPointer if document contains annotations with source=null

### ISSUE THREAD

**Issue by devfoo-one** [sebastianarnold/TeXoo#33]
https://github.com/sebastianarnold/TeXoo/blob/475073e75a0ccfc1b39d9fc4504f07493b56ada1/texoo-core/src/main/java/de/datexis/model/Document.java#L410

**Comment by sebastianarnold** [comment]
Did you set the source to `null` explicilty or did you load it from a Dataset?

**Comment by devfoo-one** [comment]
I loaded it from a Dataset with annotations that had source=null set.
