### ISSUE TITLE
Problems with SetBackwardOracleMatching

### ISSUE THREAD

**Issue by almondtools** [sebastianarnold/TeXoo#39]
While scanning the usage of stringsearchalgorithms I found your implementation of [MatchingAnnotator](https://github.com/sebastianarnold/TeXoo/blob/8ece8c953b2046dd25fdf8e436aa18d5d834ddeb/texoo-entity-recognition/src/main/java/de/datexis/ner/MatchingAnnotator.java).

It is containing a comment: `// SetBackwardOracleMatching - suoer fast, but invalid LONGEST_MATCH`. Yet the claim of every algorithm was to provide correct results (the same for each algorithm), so I would be really interested whether you found an edge case that is not yet covered by the tests.

**Comment by sebastianarnold** [comment]
Hi, thanks for jumping in here – I finally found the time to isolate the problem and reported in https://github.com/almondtools/stringsearchalgorithms/issues/9
